config/routes.rb
Rails.application.routes.draw do
root :to => 'costumes#index'
  resources :costumes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/costume.rb
class Costume < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/costumes_controller.rb
class CostumesController < ApplicationController
  before_action :set_costume, only: [:show, :edit, :update, :destroy]

  # GET /costumes
  # GET /costumes.json
  def index
    @costumes = Costume.all
  end

  # GET /costumes/1
  # GET /costumes/1.json
  def show
  end

  # GET /costumes/new
  def new
    @costume = Costume.new
  end

  # GET /costumes/1/edit
  def edit
  end

  # POST /costumes
  # POST /costumes.json
  def create
    @costume = Costume.new(costume_params)

    respond_to do |format|
      if @costume.save
        format.html { redirect_to @costume, notice: 'Costume was successfully created.' }
        format.json { render :show, status: :created, location: @costume }
      else
        format.html { render :new }
        format.json { render json: @costume.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costumes/1
  # PATCH/PUT /costumes/1.json
  def update
    respond_to do |format|
      if @costume.update(costume_params)
        format.html { redirect_to @costume, notice: 'Costume was successfully updated.' }
        format.json { render :show, status: :ok, location: @costume }
      else
        format.html { render :edit }
        format.json { render json: @costume.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costumes/1
  # DELETE /costumes/1.json
  def destroy
    @costume.destroy
    respond_to do |format|
      format.html { redirect_to costumes_url, notice: 'Costume was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_costume
      @costume = Costume.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def costume_params
      params.require(:costume).permit(:name, :item, :url, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/costumes_helper.rb
module CostumesHelper
end

app/views/costumes/_form.html.erb
<%= form_with(model: costume, local: true) do |form| %>
  <% if costume.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(costume.errors.count, "error") %> prohibited this costume from being saved:</h2>

      <ul>
      <% costume.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :costume_name %>
  </div>

  <div class="field">
    <%= form.label :item %>
    <%= form.text_field :item, id: :costume_item %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :costume_url %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment, id: :costume_comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/costumes/edit.html.erb
<h1>Editing Costume</h1>

<%= render 'form', costume: @costume %>

<%= link_to 'Show', @costume %> |
<%= link_to 'Back', costumes_path %>

app/views/costumes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Costumes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Item</th>
      <th>Url</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costumes.each do |costume| %>
      <tr>
        <td><%= costume.name %></td>
        <td><%= costume.item %></td>
        <td><%= costume.url %></td>
        <td><%= costume.comment %></td>
        <td><%= link_to 'Show', costume %></td>
        <td><%= link_to 'Edit', edit_costume_path(costume) %></td>
        <td><%= link_to 'Destroy', costume, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Costume', new_costume_path %>

app/views/costumes/new.html.erb
<h1>New Costume</h1>

<%= render 'form', costume: @costume %>

<%= link_to 'Back', costumes_path %>

app/views/costumes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @costume.name %>
</p>

<p>
  <strong>Item:</strong>
  <%= @costume.item %>
</p>

<p>
  <strong>Url:</strong>
  <%= @costume.url %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @costume.comment %>
</p>

<%= link_to 'Edit', edit_costume_path(@costume) %> |
<%= link_to 'Back', costumes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tws</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>